#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Create an index.html file with the "Hello World!" message
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Start Nginx
sudo service nginx start
