#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World inside

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default

service nginx restart
