#!/usr/bin/env bash
#to configure a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "13i\\\n\tserver {\n\t\t#server configuration\n\n\t\tadd_header X-Served-By $HOSTNAME;\n\t}\n\n" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
