#!/usr/bin/env bash
# Install the load balancer


sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get install haproxy=2.6.\*

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\nfrontend http-in\n\tbind *:80\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 125958-web-01 54.160.113.254:80 check\n\tserver 125958-web-02 18.204.10.93:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy start