#!/usr/bin/env bash
# Install the load balancer


apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 125958-web-01 54.90.53.130:80 check\n\tserver 125958-web-02 34.232.65.110:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart