#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Create a new DNS resolver configuration file
echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "nameserver 127.0.0.2" >> /etc/resolv.conf

# Add entries to the /etc/hosts file to resolve localhost and facebook.com
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
